2014-01-04 22:08:38 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /SalvatoresPizza/css/cake.customer.css
Stack Trace:
#0 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-04 22:08:41 Error: [MissingControllerException] Controller class ImgController could not be found.
Exception Attributes: array (
  'class' => 'ImgController',
  'plugin' => NULL,
)
Request URL: /SalvatoresPizza/img/SalvatoresBanner.png
Stack Trace:
#0 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-04 22:09:29 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /SalvatoresPizza/css/cake.customer.css
Stack Trace:
#0 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-04 22:09:29 Error: [MissingControllerException] Controller class ImgController could not be found.
Exception Attributes: array (
  'class' => 'ImgController',
  'plugin' => NULL,
)
Request URL: /SalvatoresPizza/img/SalvatoresBanner.png
Stack Trace:
#0 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-04 22:11:42 Error: [MissingControllerException] Controller class ImgController could not be found.
Exception Attributes: array (
  'class' => 'ImgController',
  'plugin' => NULL,
)
Request URL: /SalvatoresPizza/img/SalvatoresBanner.png
Stack Trace:
#0 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-04 22:12:57 Error: [MissingViewException] View file "F:\xampp\htdocs\SalvatoresPizza\View\Pages\reviews.ctp" is missing.
Exception Attributes: array (
  'file' => 'F:\\xampp\\htdocs\\SalvatoresPizza\\View\\Pages\\reviews.ctp',
)
Request URL: /SalvatoresPizza/reviews
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\View\View.php(459): View->_getViewFileName('reviews')
#1 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(952): View->render('reviews', NULL)
#2 F:\xampp\htdocs\SalvatoresPizza\Controller\PagesController.php(62): Controller->render('reviews')
#3 [internal function]: PagesController->display('reviews')
#4 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PagesController), Array)
#5 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#6 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest), Object(CakeResponse))
#7 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2014-01-04 22:13:18 Error: [MissingControllerException] Controller class ImgController could not be found.
Exception Attributes: array (
  'class' => 'ImgController',
  'plugin' => NULL,
)
Request URL: /SalvatoresPizza/img/SalvatoresBanner.png
Stack Trace:
#0 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-04 22:13:44 Error: [MissingControllerException] Controller class ImgController could not be found.
Exception Attributes: array (
  'class' => 'ImgController',
  'plugin' => NULL,
)
Request URL: /SalvatoresPizza/img/SalvatoresBanner.png
Stack Trace:
#0 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-04 22:45:51 Error: [MissingViewException] View file "F:\xampp\htdocs\SalvatoresPizza\View\Pages\reviews.ctp" is missing.
Exception Attributes: array (
  'file' => 'F:\\xampp\\htdocs\\SalvatoresPizza\\View\\Pages\\reviews.ctp',
)
Request URL: /SalvatoresPizza/reviews
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\View\View.php(459): View->_getViewFileName('reviews')
#1 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(952): View->render('reviews', NULL)
#2 F:\xampp\htdocs\SalvatoresPizza\Controller\PagesController.php(62): Controller->render('reviews')
#3 [internal function]: PagesController->display('reviews')
#4 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PagesController), Array)
#5 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#6 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest), Object(CakeResponse))
#7 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2014-01-04 22:46:41 Error: [MissingViewException] View file "F:\xampp\htdocs\SalvatoresPizza\View\Pages\reviews.ctp" is missing.
Exception Attributes: array (
  'file' => 'F:\\xampp\\htdocs\\SalvatoresPizza\\View\\Pages\\reviews.ctp',
)
Request URL: /SalvatoresPizza/reviews
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\View\View.php(459): View->_getViewFileName('reviews')
#1 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(952): View->render('reviews', NULL)
#2 F:\xampp\htdocs\SalvatoresPizza\Controller\PagesController.php(62): Controller->render('reviews')
#3 [internal function]: PagesController->display('reviews')
#4 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PagesController), Array)
#5 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#6 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest), Object(CakeResponse))
#7 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2014-01-04 22:50:01 Error: [MissingViewException] View file "F:\xampp\htdocs\SalvatoresPizza\View\Pages\reviews.ctp" is missing.
Exception Attributes: array (
  'file' => 'F:\\xampp\\htdocs\\SalvatoresPizza\\View\\Pages\\reviews.ctp',
)
Request URL: /SalvatoresPizza/reviews
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\View\View.php(459): View->_getViewFileName('reviews')
#1 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(952): View->render('reviews', NULL)
#2 F:\xampp\htdocs\SalvatoresPizza\Controller\PagesController.php(63): Controller->render('reviews')
#3 [internal function]: PagesController->display('reviews')
#4 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PagesController), Array)
#5 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#6 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest), Object(CakeResponse))
#7 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2014-01-04 22:50:05 Error: [MissingViewException] View file "F:\xampp\htdocs\SalvatoresPizza\View\Pages\reviews.ctp" is missing.
Exception Attributes: array (
  'file' => 'F:\\xampp\\htdocs\\SalvatoresPizza\\View\\Pages\\reviews.ctp',
)
Request URL: /SalvatoresPizza/reviews
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\View\View.php(459): View->_getViewFileName('reviews')
#1 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(952): View->render('reviews', NULL)
#2 F:\xampp\htdocs\SalvatoresPizza\Controller\PagesController.php(63): Controller->render('reviews')
#3 [internal function]: PagesController->display('reviews')
#4 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PagesController), Array)
#5 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#6 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest), Object(CakeResponse))
#7 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2014-01-05 23:14:30 Error: [MissingViewException] View file "F:\xampp\htdocs\SalvatoresPizza\View\Users\login.ctp" is missing.
Exception Attributes: array (
  'file' => 'F:\\xampp\\htdocs\\SalvatoresPizza\\View\\Users\\login.ctp',
)
Request URL: /SalvatoresPizza/users/login
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\View\View.php(459): View->_getViewFileName(NULL)
#1 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(194): Controller->render()
#3 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-05 23:26:44 Error: [MissingViewException] View file "F:\xampp\htdocs\SalvatoresPizza\View\Users\login.ctp" is missing.
Exception Attributes: array (
  'file' => 'F:\\xampp\\htdocs\\SalvatoresPizza\\View\\Users\\login.ctp',
)
Request URL: /SalvatoresPizza/users/login
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\View\View.php(459): View->_getViewFileName(NULL)
#1 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(194): Controller->render()
#3 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-05 23:35:41 Error: [MissingActionException] Action UsersController::addbackoffice() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'addbackoffice',
)
Request URL: /SalvatoresPizza/users/addbackoffice
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#1 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-06 06:23:51 Error: [MissingPluginException] Plugin AclExtras could not be found.
Exception Attributes: array (
  'plugin' => 'AclExtras',
)
Stack Trace:
#0 F:\xampp\htdocs\SalvatoresPizza\Config\bootstrap.php(82): CakePlugin::load('AclExtras')
#1 C:\cake\cakephp-2.4.0\lib\Cake\Core\Configure.php(92): include('F:\xampp\htdocs...')
#2 C:\cake\cakephp-2.4.0\lib\Cake\bootstrap.php(177): Configure::bootstrap(true)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Console\ShellDispatcher.php(138): require('C:\cake\cakephp...')
#4 C:\cake\cakephp-2.4.0\lib\Cake\Console\ShellDispatcher.php(100): ShellDispatcher->_bootstrap()
#5 C:\cake\cakephp-2.4.0\lib\Cake\Console\ShellDispatcher.php(56): ShellDispatcher->_initEnvironment()
#6 C:\cake\cakephp-2.4.0\lib\Cake\Console\ShellDispatcher.php(67): ShellDispatcher->__construct(Array)
#7 C:\cake\cakephp-2.4.0\app\Console\cake.php(37): ShellDispatcher::run(Array)
#8 {main}
2014-01-06 06:52:02 Error: [MissingActionException] Action UsersController::home() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'home',
)
Request URL: /SalvatoresPizza/users/home
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#1 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-06 18:45:06 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.username' in 'where clause'
Request URL: /SalvatoresPizza/users/login
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `User`.`...', Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `User`.`...', false)
#4 C:\cake\cakephp-2.4.0\lib\Cake\Model\Model.php(2750): DboSource->read(Object(User), Array)
#5 C:\cake\cakephp-2.4.0\lib\Cake\Model\Model.php(2722): Model->_readDataSource('first', Array)
#6 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Component\Auth\BaseAuthenticate.php(114): Model->find('first', Array)
#7 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Component\Auth\FormAuthenticate.php(81): BaseAuthenticate->_findUser('rbarnett@samfor...', 'Samue1Jackson')
#8 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Component\AuthComponent.php(754): FormAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#9 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Component\AuthComponent.php(601): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#10 F:\xampp\htdocs\SalvatoresPizza\Controller\UsersController.php(169): AuthComponent->login()
#11 [internal function]: UsersController->login()
#12 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#13 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#14 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#15 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2014-01-06 18:45:20 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.username' in 'where clause'
Request URL: /SalvatoresPizza/users/login
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `User`.`...', Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `User`.`...', false)
#4 C:\cake\cakephp-2.4.0\lib\Cake\Model\Model.php(2750): DboSource->read(Object(User), Array)
#5 C:\cake\cakephp-2.4.0\lib\Cake\Model\Model.php(2722): Model->_readDataSource('first', Array)
#6 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Component\Auth\BaseAuthenticate.php(114): Model->find('first', Array)
#7 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Component\Auth\FormAuthenticate.php(81): BaseAuthenticate->_findUser('rbarnett', 'Samue1Jackson')
#8 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Component\AuthComponent.php(754): FormAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#9 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Component\AuthComponent.php(601): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#10 F:\xampp\htdocs\SalvatoresPizza\Controller\UsersController.php(169): AuthComponent->login()
#11 [internal function]: UsersController->login()
#12 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#13 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#14 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#15 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2014-01-06 18:46:06 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.username' in 'where clause'
Request URL: /SalvatoresPizza/users/login
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `User`.`...', Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `User`.`...', false)
#4 C:\cake\cakephp-2.4.0\lib\Cake\Model\Model.php(2750): DboSource->read(Object(User), Array)
#5 C:\cake\cakephp-2.4.0\lib\Cake\Model\Model.php(2722): Model->_readDataSource('first', Array)
#6 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Component\Auth\BaseAuthenticate.php(114): Model->find('first', Array)
#7 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Component\Auth\FormAuthenticate.php(81): BaseAuthenticate->_findUser('rbarnett@samfor...', 'Samue1Jackson')
#8 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Component\AuthComponent.php(754): FormAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#9 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Component\AuthComponent.php(601): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#10 F:\xampp\htdocs\SalvatoresPizza\Controller\UsersController.php(169): AuthComponent->login()
#11 [internal function]: UsersController->login()
#12 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#13 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#14 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#15 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2014-01-06 18:49:18 Error: [NotFoundException] Invalid user
Request URL: /SalvatoresPizza/users/delete
Stack Trace:
#0 [internal function]: UsersController->delete()
#1 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#3 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-06 18:49:35 Error: [NotFoundException] Invalid user
Request URL: /SalvatoresPizza/users/edit
Stack Trace:
#0 [internal function]: UsersController->edit()
#1 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#3 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-06 18:50:23 Error: [NotFoundException] Invalid user
Request URL: /SalvatoresPizza/users/edit
Stack Trace:
#0 [internal function]: UsersController->edit()
#1 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#3 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-06 18:50:41 Error: [NotFoundException] Invalid user
Request URL: /SalvatoresPizza/users/edit
Stack Trace:
#0 [internal function]: UsersController->edit()
#1 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#3 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-06 18:50:49 Error: [MissingActionException] Action UsersController::indexbackoffice() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'indexbackoffice',
)
Request URL: /SalvatoresPizza/users/indexbackoffice
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#1 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-06 19:01:59 Error: [NotFoundException] Invalid user
Request URL: /SalvatoresPizza/users/delete
Stack Trace:
#0 [internal function]: UsersController->delete()
#1 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#3 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-06 19:15:02 Error: [MissingActionException] Action MenuCategoriesController::indexbackoffice() could not be found.
Exception Attributes: array (
  'controller' => 'MenuCategoriesController',
  'action' => 'indexbackoffice',
)
Request URL: /SalvatoresPizza/menucategories/indexbackoffice
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#1 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MenuCategoriesController), Object(CakeRequest), Object(CakeResponse))
#2 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-06 23:35:09 Error: [MissingActionException] Action MenuCategoriesController::orders() could not be found.
Exception Attributes: array (
  'controller' => 'MenuCategoriesController',
  'action' => 'orders',
)
Request URL: /SalvatoresPizza/menucategories/orders/add
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#1 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MenuCategoriesController), Object(CakeRequest), Object(CakeResponse))
#2 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-07 04:14:22 Error: [MissingActionException] Action MenuItemsController::entrees() could not be found.
Exception Attributes: array (
  'controller' => 'MenuItemsController',
  'action' => 'entrees',
)
Request URL: /SalvatoresPizza/menuitems/entrees
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#1 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MenuItemsController), Object(CakeRequest), Object(CakeResponse))
#2 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-08 00:32:40 Error: [MissingViewException] View file "F:\xampp\htdocs\SalvatoresPizza\View\OrderDetails\addtocart.ctp" is missing.
Exception Attributes: array (
  'file' => 'F:\\xampp\\htdocs\\SalvatoresPizza\\View\\OrderDetails\\addtocart.ctp',
)
Request URL: /SalvatoresPizza/orderdetails/addtocart/6
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\View\View.php(459): View->_getViewFileName(NULL)
#1 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(194): Controller->render()
#3 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(OrderDetailsController), Object(CakeRequest), Object(CakeResponse))
#4 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-08 00:51:46 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Order.user' in 'where clause'
Request URL: /SalvatoresPizza/orderdetails/addtocart/13
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Order`....', Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `Order`....', Array, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `Order`....', false)
#4 C:\cake\cakephp-2.4.0\lib\Cake\Model\Model.php(2750): DboSource->read(Object(Order), Array)
#5 C:\cake\cakephp-2.4.0\lib\Cake\Model\Model.php(2722): Model->_readDataSource('all', Array)
#6 F:\xampp\htdocs\SalvatoresPizza\Controller\OrderDetailsController.php(36): Model->find('all', Array)
#7 [internal function]: OrderDetailsController->addtocart('13')
#8 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(OrderDetailsController), Array)
#9 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#10 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(OrderDetailsController), Object(CakeRequest), Object(CakeResponse))
#11 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-01-08 00:56:19 Error: Fatal Error (1): Function name must be a string in [F:\xampp\htdocs\SalvatoresPizza\Controller\OrderDetailsController.php, line 37]
2014-01-08 00:56:19 Error: [FatalErrorException] Function name must be a string
Request URL: /SalvatoresPizza/orderdetails/addtocart/13
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Function name m...', 'F:\xampp\htdocs...', 37)
#1 [internal function]: ErrorHandler::handleError(1, 'Function name m...', 'F:\xampp\htdocs...', 37, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Function name m...', 'F:\xampp\htdocs...', 37, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-08 04:39:14 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous
Request URL: /SalvatoresPizza/orderdetails/addtocart/13
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `MenuIte...', Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `MenuIte...', Array, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `MenuIte...', false)
#4 C:\cake\cakephp-2.4.0\lib\Cake\Model\Model.php(2750): DboSource->read(Object(MenuItem), Array)
#5 C:\cake\cakephp-2.4.0\lib\Cake\Model\Model.php(2722): Model->_readDataSource('all', Array)
#6 F:\xampp\htdocs\SalvatoresPizza\Controller\OrderDetailsController.php(48): Model->find('all', Array)
#7 [internal function]: OrderDetailsController->addtocart('13')
#8 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(OrderDetailsController), Array)
#9 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#10 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(OrderDetailsController), Object(CakeRequest), Object(CakeResponse))
#11 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-01-08 05:03:43 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`salvatoresdata`.`orders`, CONSTRAINT `fk_orders_users1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
Request URL: /SalvatoresPizza/orderdetails/addtocart/13
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('INSERT INTO `sa...', Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(1004): DboSource->execute('INSERT INTO `sa...')
#3 C:\cake\cakephp-2.4.0\lib\Cake\Model\Model.php(1761): DboSource->create(Object(Order), Array, Array)
#4 F:\xampp\htdocs\SalvatoresPizza\Controller\OrderDetailsController.php(47): Model->save()
#5 [internal function]: OrderDetailsController->addtocart('13')
#6 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(OrderDetailsController), Array)
#7 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#8 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(OrderDetailsController), Object(CakeRequest), Object(CakeResponse))
#9 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-01-08 05:05:53 Error: [MissingControllerException] Controller class OrdesController could not be found.
Exception Attributes: array (
  'class' => 'OrdesController',
  'plugin' => NULL,
)
Request URL: /SalvatoresPizza/ordes
Stack Trace:
#0 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-08 06:42:01 Error: Fatal Error (1): Unsupported operand types in [C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php, line 848]
2014-01-08 06:42:01 Error: [FatalErrorException] Unsupported operand types
Request URL: /SalvatoresPizza/calzones
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\cake\cakephp...', 848)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\cake\cakephp...', 848, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\cake\cakephp...', 848, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-08 07:06:57 Error: [NotFoundException] Invalid order
Request URL: /SalvatoresPizza/orders/delete/13
Stack Trace:
#0 [internal function]: OrdersController->delete('13')
#1 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(OrdersController), Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#3 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(OrdersController), Object(CakeRequest), Object(CakeResponse))
#4 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-08 07:26:05 Error: [NotFoundException] Invalid order
Request URL: /SalvatoresPizza/orders/delete/16
Stack Trace:
#0 [internal function]: OrdersController->delete('16')
#1 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(OrdersController), Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#3 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(OrdersController), Object(CakeRequest), Object(CakeResponse))
#4 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-08 07:26:18 Error: [NotFoundException] Invalid order
Request URL: /SalvatoresPizza/orders/delete
Stack Trace:
#0 [internal function]: OrdersController->delete()
#1 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(OrdersController), Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#3 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(OrdersController), Object(CakeRequest), Object(CakeResponse))
#4 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-08 19:16:55 Error: Fatal Error (1): Call to a member function find() on a non-object in [F:\xampp\htdocs\SalvatoresPizza\Controller\OrderDetailsController.php, line 78]
2014-01-08 19:16:55 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /SalvatoresPizza/orderdetails/viewcart/1
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'F:\xampp\htdocs...', 78)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'F:\xampp\htdocs...', 78, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'F:\xampp\htdocs...', 78, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-08 19:17:33 Error: [MissingModelException] Model Array could not be found.
Exception Attributes: array (
  0 => 
  array (
    'OrderDetail' => 
    array (
      'id' => '1',
      'order_id' => '20',
      'menu_item_id' => '153',
      'price' => '3',
    ),
    'Order' => 
    array (
      'id' => '20',
      'user_id' => '3',
      'location_id' => '1',
      'orderdate' => '2014-01-08 18:18:17',
      'stage_id' => '1',
      'total' => '3',
      'paid' => '3',
    ),
    'MenuItem' => 
    array (
      'id' => '153',
      'menu_category_id' => '28',
      'order' => '1',
      'title' => 'Cheese',
      'tagline' => '',
      'price' => '3',
      'dateforspecial' => '2014-01-07 05:30:00',
    ),
    'OrderDetailTopping' => 
    array (
    ),
  ),
  1 => 
  array (
    'OrderDetail' => 
    array (
      'id' => '3',
      'order_id' => '20',
      'menu_item_id' => '26',
      'price' => '4.95',
    ),
    'Order' => 
    array (
      'id' => '20',
      'user_id' => '3',
      'location_id' => '1',
      'orderdate' => '2014-01-08 18:18:17',
      'stage_id' => '1',
      'total' => '3',
      'paid' => '3',
    ),
    'MenuItem' => 
    array (
      'id' => '26',
      'menu_category_id' => '8',
      'order' => '5',
      'title' => 'White Chocolate Bread Pudding',
      'tagline' => '',
      'price' => '4.95',
      'dateforspecial' => '2014-01-06 23:57:00',
    ),
    'OrderDetailTopping' => 
    array (
    ),
  ),
  2 => 
  array (
    'OrderDetail' => 
    array (
      'id' => '4',
      'order_id' => '20',
      'menu_item_id' => '22',
      'price' => '4.95',
    ),
    'Order' => 
    array (
      'id' => '20',
      'user_id' => '3',
      'location_id' => '1',
      'orderdate' => '2014-01-08 18:18:17',
      'stage_id' => '1',
      'total' => '3',
      'paid' => '3',
    ),
    'MenuItem' => 
    array (
      'id' => '22',
      'menu_category_id' => '8',
      'order' => '2',
      'title' => 'Double Chocolate Mousse Cake',
      'tagline' => '',
      'price' => '4.95',
      'dateforspecial' => '2014-01-06 23:54:00',
    ),
    'OrderDetailTopping' => 
    array (
    ),
  ),
  3 => 
  array (
    'OrderDetail' => 
    array (
      'id' => '6',
      'order_id' => '20',
      'menu_item_id' => '68',
      'price' => '8.25',
    ),
    'Order' => 
    array (
      'id' => '20',
      'user_id' => '3',
      'location_id' => '1',
      'orderdate' => '2014-01-08 18:18:17',
      'stage_id' => '1',
      'total' => '3',
      'paid' => '3',
    ),
    'MenuItem' => 
    array (
      'id' => '68',
      'menu_category_id' => '15',
      'order' => '4',
      'title' => 'Baked Ziti with Mozzarella,Ricotta & Parmesa',
      'tagline' => '',
      'price' => '8.25',
      'dateforspecial' => '2014-01-07 03:44:00',
    ),
    'OrderDetailTopping' => 
    array (
    ),
  ),
)
Request URL: /SalvatoresPizza/orderdetails/viewcart/1
Stack Trace:
#0 F:\xampp\htdocs\SalvatoresPizza\Controller\OrderDetailsController.php(88): PaginatorComponent->paginate()
#1 [internal function]: OrderDetailsController->viewcart('1')
#2 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(OrderDetailsController), Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#4 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(OrderDetailsController), Object(CakeRequest), Object(CakeResponse))
#5 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-01-08 20:00:00 Error: [NotFoundException] Invalid order detail
Request URL: /SalvatoresPizza/orderdetails/delete/7
Stack Trace:
#0 [internal function]: OrderDetailsController->delete('7')
#1 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(OrderDetailsController), Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#3 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(OrderDetailsController), Object(CakeRequest), Object(CakeResponse))
#4 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-09 00:00:18 Error: Fatal Error (1): Call to a member function find() on a non-object in [F:\xampp\htdocs\SalvatoresPizza\Controller\OrderDetailsController.php, line 88]
2014-01-09 00:00:18 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /SalvatoresPizza/orderdetails/viewcart/1
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'F:\xampp\htdocs...', 88)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'F:\xampp\htdocs...', 88, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'F:\xampp\htdocs...', 88, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-09 00:16:26 Error: [MissingHelperException] Helper class AuthHelper could not be found.
Exception Attributes: array (
  'class' => 'AuthHelper',
  'plugin' => false,
)
Request URL: /SalvatoresPizza/users/login
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\View\HelperCollection.php(63): HelperCollection->load('Auth')
#1 C:\cake\cakephp-2.4.0\lib\Cake\View\View.php(818): HelperCollection->__isset('Auth')
#2 F:\xampp\htdocs\SalvatoresPizza\View\Elements\loginButtons.ctp(16): View->__get('Auth')
#3 C:\cake\cakephp-2.4.0\lib\Cake\View\View.php(929): include('F:\xampp\htdocs...')
#4 C:\cake\cakephp-2.4.0\lib\Cake\View\View.php(891): View->_evaluate('F:\xampp\htdocs...', Array)
#5 C:\cake\cakephp-2.4.0\lib\Cake\View\View.php(1189): View->_render('F:\xampp\htdocs...', Array)
#6 C:\cake\cakephp-2.4.0\lib\Cake\View\View.php(408): View->_renderElement('F:\xampp\htdocs...', Array, Array)
#7 F:\xampp\htdocs\SalvatoresPizza\View\Layouts\customer.ctp(28): View->element('loginButtons')
#8 C:\cake\cakephp-2.4.0\lib\Cake\View\View.php(929): include('F:\xampp\htdocs...')
#9 C:\cake\cakephp-2.4.0\lib\Cake\View\View.php(891): View->_evaluate('F:\xampp\htdocs...', Array)
#10 C:\cake\cakephp-2.4.0\lib\Cake\View\View.php(523): View->_render('F:\xampp\htdocs...')
#11 C:\cake\cakephp-2.4.0\lib\Cake\View\View.php(470): View->renderLayout('', 'customer')
#12 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#13 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(194): Controller->render()
#14 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#15 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2014-01-09 00:26:23 Error: Fatal Error (1): Call to undefined method View::loadModel() in [F:\xampp\htdocs\SalvatoresPizza\View\Elements\loginButtons.ctp, line 12]
2014-01-09 00:26:23 Error: [FatalErrorException] Call to undefined method View::loadModel()
Request URL: /SalvatoresPizza/menucategories/home
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'F:\xampp\htdocs...', 12)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'F:\xampp\htdocs...', 12, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'F:\xampp\htdocs...', 12, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-10 04:32:28 Error: Fatal Error (1): Maximum execution time of 30 seconds exceeded in [C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php, line 458]
2014-01-10 04:32:29 Error: [FatalErrorException] Maximum execution time of 30 seconds exceeded
Request URL: /SalvatoresPizza/users/logout
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Maximum executi...', 'C:\cake\cakephp...', 458)
#1 [internal function]: ErrorHandler::handleError(1, 'Maximum executi...', 'C:\cake\cakephp...', 458, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Maximum executi...', 'C:\cake\cakephp...', 458, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-10 04:32:38 Error: Fatal Error (1): Maximum execution time of 30 seconds exceeded in [C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php, line 460]
2014-01-10 04:32:38 Error: [FatalErrorException] Maximum execution time of 30 seconds exceeded
Request URL: /SalvatoresPizza/users/logout
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Maximum executi...', 'C:\cake\cakephp...', 460)
#1 [internal function]: ErrorHandler::handleError(1, 'Maximum executi...', 'C:\cake\cakephp...', 460, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Maximum executi...', 'C:\cake\cakephp...', 460, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-10 21:54:39 Error: Fatal Error (1): Class 'CakeEmail' not found in [F:\xampp\htdocs\SalvatoresPizza\Controller\MenuCategoriesController.php, line 34]
2014-01-10 21:54:39 Error: [FatalErrorException] Class 'CakeEmail' not found
Request URL: /SalvatoresPizza/menucategories/testemail
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Class 'CakeEmai...', 'F:\xampp\htdocs...', 34)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'CakeEmai...', 'F:\xampp\htdocs...', 34, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Class 'CakeEmai...', 'F:\xampp\htdocs...', 34, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-10 21:56:15 Error: Fatal Error (1): Class 'CakeEmail' not found in [F:\xampp\htdocs\SalvatoresPizza\Controller\MenuCategoriesController.php, line 34]
2014-01-10 21:56:15 Error: [FatalErrorException] Class 'CakeEmail' not found
Request URL: /SalvatoresPizza/menucategories/testemail
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Class 'CakeEmai...', 'F:\xampp\htdocs...', 34)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'CakeEmai...', 'F:\xampp\htdocs...', 34, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Class 'CakeEmai...', 'F:\xampp\htdocs...', 34, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-10 21:58:15 Error: [SocketException] From is not specified.
Request URL: /SalvatoresPizza/menucategories/testemail
Stack Trace:
#0 F:\xampp\htdocs\SalvatoresPizza\Controller\MenuCategoriesController.php(38): CakeEmail->send('Email testing c...')
#1 [internal function]: MenuCategoriesController->testemail()
#2 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(MenuCategoriesController), Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#4 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MenuCategoriesController), Object(CakeRequest), Object(CakeResponse))
#5 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-01-10 21:59:39 Error: [ConfigureException] Unknown email configuration "email".
Request URL: /SalvatoresPizza/menucategories/testemail
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Network\Email\CakeEmail.php(1088): CakeEmail->_applyConfig('email')
#1 C:\cake\cakephp-2.4.0\lib\Cake\Network\Email\CakeEmail.php(345): CakeEmail->config('email')
#2 F:\xampp\htdocs\SalvatoresPizza\Controller\MenuCategoriesController.php(35): CakeEmail->__construct('email')
#3 [internal function]: MenuCategoriesController->testemail()
#4 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(MenuCategoriesController), Array)
#5 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#6 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MenuCategoriesController), Object(CakeRequest), Object(CakeResponse))
#7 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2014-01-10 22:00:03 Error: [ConfigureException] Unknown email configuration "email.php".
Request URL: /SalvatoresPizza/menucategories/testemail
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Network\Email\CakeEmail.php(1088): CakeEmail->_applyConfig('email.php')
#1 C:\cake\cakephp-2.4.0\lib\Cake\Network\Email\CakeEmail.php(345): CakeEmail->config('email.php')
#2 F:\xampp\htdocs\SalvatoresPizza\Controller\MenuCategoriesController.php(35): CakeEmail->__construct('email.php')
#3 [internal function]: MenuCategoriesController->testemail()
#4 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(MenuCategoriesController), Array)
#5 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#6 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MenuCategoriesController), Object(CakeRequest), Object(CakeResponse))
#7 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2014-01-10 22:02:42 Error: [SocketException] From is not specified.
Request URL: /SalvatoresPizza/menucategories/testemail
Stack Trace:
#0 F:\xampp\htdocs\SalvatoresPizza\Controller\MenuCategoriesController.php(38): CakeEmail->send('Email testing c...')
#1 [internal function]: MenuCategoriesController->testemail()
#2 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(MenuCategoriesController), Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#4 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MenuCategoriesController), Object(CakeRequest), Object(CakeResponse))
#5 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-01-10 22:03:56 Error: [SocketException] From is not specified.
Request URL: /SalvatoresPizza/menucategories/testemail
Stack Trace:
#0 F:\xampp\htdocs\SalvatoresPizza\Controller\MenuCategoriesController.php(38): CakeEmail->send('Email testing c...')
#1 [internal function]: MenuCategoriesController->testemail()
#2 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(MenuCategoriesController), Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#4 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MenuCategoriesController), Object(CakeRequest), Object(CakeResponse))
#5 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-01-11 06:27:28 Error: Fatal Error (1): Function name must be a string in [F:\xampp\htdocs\SalvatoresPizza\Controller\MenuItemsController.php, line 146]
2014-01-11 06:27:28 Error: [FatalErrorException] Function name must be a string
Request URL: /SalvatoresPizza/menuitems/add
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Function name m...', 'F:\xampp\htdocs...', 146)
#1 [internal function]: ErrorHandler::handleError(1, 'Function name m...', 'F:\xampp\htdocs...', 146, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Function name m...', 'F:\xampp\htdocs...', 146, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-11 06:28:07 Error: Fatal Error (1): Call to undefined method MenuItemsController::debug() in [F:\xampp\htdocs\SalvatoresPizza\Controller\MenuItemsController.php, line 146]
2014-01-11 06:28:07 Error: [FatalErrorException] Call to undefined method MenuItemsController::debug()
Request URL: /SalvatoresPizza/menuitems/add
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'F:\xampp\htdocs...', 146)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'F:\xampp\htdocs...', 146, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'F:\xampp\htdocs...', 146, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-11 06:31:13 Error: Fatal Error (1): Function name must be a string in [F:\xampp\htdocs\SalvatoresPizza\Controller\MenuItemsController.php, line 146]
2014-01-11 06:31:13 Error: [FatalErrorException] Function name must be a string
Request URL: /SalvatoresPizza/menuitems/add
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Function name m...', 'F:\xampp\htdocs...', 146)
#1 [internal function]: ErrorHandler::handleError(1, 'Function name m...', 'F:\xampp\htdocs...', 146, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Function name m...', 'F:\xampp\htdocs...', 146, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-11 06:33:37 Error: Fatal Error (1): Function name must be a string in [F:\xampp\htdocs\SalvatoresPizza\Controller\MenuItemsController.php, line 146]
2014-01-11 06:33:37 Error: [FatalErrorException] Function name must be a string
Request URL: /SalvatoresPizza/menuitems/add
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Function name m...', 'F:\xampp\htdocs...', 146)
#1 [internal function]: ErrorHandler::handleError(1, 'Function name m...', 'F:\xampp\htdocs...', 146, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Function name m...', 'F:\xampp\htdocs...', 146, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-11 06:34:19 Error: Fatal Error (1): Call to undefined method MenuItemsController::debug() in [F:\xampp\htdocs\SalvatoresPizza\Controller\MenuItemsController.php, line 146]
2014-01-11 06:34:19 Error: [FatalErrorException] Call to undefined method MenuItemsController::debug()
Request URL: /SalvatoresPizza/menuitems/add
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'F:\xampp\htdocs...', 146)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'F:\xampp\htdocs...', 146, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'F:\xampp\htdocs...', 146, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-11 06:34:51 Error: Fatal Error (1): Call to undefined method MenuItemsController::debug() in [F:\xampp\htdocs\SalvatoresPizza\Controller\MenuItemsController.php, line 146]
2014-01-11 06:34:51 Error: [FatalErrorException] Call to undefined method MenuItemsController::debug()
Request URL: /SalvatoresPizza/menuitems/add
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'F:\xampp\htdocs...', 146)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'F:\xampp\htdocs...', 146, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'F:\xampp\htdocs...', 146, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-14 19:21:45 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Toppings.item' in 'where clause'
Request URL: /SalvatoresPizza/orderdetails/viewcart/1
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Topping...', Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `Topping...', Array, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `Topping...', false)
#4 C:\cake\cakephp-2.4.0\lib\Cake\Model\Model.php(2750): DboSource->read(Object(Topping), Array)
#5 C:\cake\cakephp-2.4.0\lib\Cake\Model\Model.php(2722): Model->_readDataSource('list', Array)
#6 F:\xampp\htdocs\SalvatoresPizza\Controller\OrderDetailsController.php(102): Model->find('list', Array)
#7 [internal function]: OrderDetailsController->viewcart('1')
#8 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(OrderDetailsController), Array)
#9 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#10 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(OrderDetailsController), Object(CakeRequest), Object(CakeResponse))
#11 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-01-14 19:22:26 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Toppings.item' in 'where clause'
Request URL: /SalvatoresPizza/orderdetails/viewcart/1
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Topping...', Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `Topping...', Array, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `Topping...', false)
#4 C:\cake\cakephp-2.4.0\lib\Cake\Model\Model.php(2750): DboSource->read(Object(Topping), Array)
#5 C:\cake\cakephp-2.4.0\lib\Cake\Model\Model.php(2722): Model->_readDataSource('list', Array)
#6 F:\xampp\htdocs\SalvatoresPizza\Controller\OrderDetailsController.php(102): Model->find('list', Array)
#7 [internal function]: OrderDetailsController->viewcart('1')
#8 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(OrderDetailsController), Array)
#9 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#10 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(OrderDetailsController), Object(CakeRequest), Object(CakeResponse))
#11 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-01-14 19:23:24 Error: Fatal Error (1): Maximum execution time of 30 seconds exceeded in [C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php, line 460]
2014-01-14 19:23:24 Error: [FatalErrorException] Maximum execution time of 30 seconds exceeded
Request URL: /SalvatoresPizza/orderdetails/viewcart/1
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Maximum executi...', 'C:\cake\cakephp...', 460)
#1 [internal function]: ErrorHandler::handleError(1, 'Maximum executi...', 'C:\cake\cakephp...', 460, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Maximum executi...', 'C:\cake\cakephp...', 460, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-14 19:25:03 Error: Fatal Error (1): Maximum execution time of 30 seconds exceeded in [C:\cake\cakephp-2.4.0\lib\Cake\Model\Datasource\DboSource.php, line 460]
2014-01-14 19:25:03 Error: [FatalErrorException] Maximum execution time of 30 seconds exceeded
Request URL: /SalvatoresPizza/orderdetails/viewcart/1
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Maximum executi...', 'C:\cake\cakephp...', 460)
#1 [internal function]: ErrorHandler::handleError(1, 'Maximum executi...', 'C:\cake\cakephp...', 460, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Maximum executi...', 'C:\cake\cakephp...', 460, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-14 19:50:03 Error: Fatal Error (1): Unsupported operand types in [C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php, line 848]
2014-01-14 19:50:03 Error: [FatalErrorException] Unsupported operand types
Request URL: /SalvatoresPizza/orderdetails/viewcart/1
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\cake\cakephp...', 848)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\cake\cakephp...', 848, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\cake\cakephp...', 848, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-14 20:05:47 Error: Fatal Error (1): Unsupported operand types in [C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php, line 848]
2014-01-14 20:05:47 Error: [FatalErrorException] Unsupported operand types
Request URL: /SalvatoresPizza/orderdetails/viewcart/1
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\cake\cakephp...', 848)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\cake\cakephp...', 848, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\cake\cakephp...', 848, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-15 06:14:53 Error: Fatal Error (1): Maximum execution time of 30 seconds exceeded in [C:\cake\cakephp-2.4.0\lib\Cake\Cache\Engine\FileEngine.php, line 343]
2014-01-15 06:14:53 Error: [FatalErrorException] Maximum execution time of 30 seconds exceeded
Request URL: /SalvatoresPizza/orderdetails/addtopping/23
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Maximum executi...', 'C:\cake\cakephp...', 343)
#1 [internal function]: ErrorHandler::handleError(1, 'Maximum executi...', 'C:\cake\cakephp...', 343, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Maximum executi...', 'C:\cake\cakephp...', 343, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-15 06:39:09 Error: [MissingControllerException] Controller class OrderdetailtoppingController could not be found.
Exception Attributes: array (
  'class' => 'OrderdetailtoppingController',
  'plugin' => NULL,
)
Request URL: /SalvatoresPizza/orderdetailtopping
Stack Trace:
#0 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-15 07:28:56 Error: [MissingControllerException] Controller class OrderDetailToppingController could not be found.
Exception Attributes: array (
  'class' => 'OrderDetailToppingController',
  'plugin' => NULL,
)
Request URL: /SalvatoresPizza/OrderDetailTopping/delete/4
Stack Trace:
#0 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-15 07:33:21 Error: Fatal Error (4): syntax error, unexpected ';' in [F:\xampp\htdocs\SalvatoresPizza\Controller\OrderDetailToppingsController.php, line 108]
2014-01-15 07:33:21 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /SalvatoresPizza/OrderDetailToppings/delete/3
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'F:\xampp\htdocs...', 108)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'F:\xampp\htdocs...', 108, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'F:\xampp\htdocs...', 108, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-15 08:01:46 Error: [MethodNotAllowedException] Method Not Allowed
Request URL: /SalvatoresPizza/OrderDetailToppings/delete/12
Stack Trace:
#0 F:\xampp\htdocs\SalvatoresPizza\Controller\OrderDetailToppingsController.php(102): CakeRequest->onlyAllow('post', 'delete')
#1 [internal function]: OrderDetailToppingsController->delete('12')
#2 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(OrderDetailToppingsController), Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#4 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(OrderDetailToppingsController), Object(CakeRequest), Object(CakeResponse))
#5 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-01-15 08:03:10 Error: [MethodNotAllowedException] Method Not Allowed
Request URL: /SalvatoresPizza/OrderDetailToppings/delete/1
Stack Trace:
#0 F:\xampp\htdocs\SalvatoresPizza\Controller\OrderDetailToppingsController.php(102): CakeRequest->onlyAllow('post', 'delete')
#1 [internal function]: OrderDetailToppingsController->delete('1')
#2 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(OrderDetailToppingsController), Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#4 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(OrderDetailToppingsController), Object(CakeRequest), Object(CakeResponse))
#5 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-01-15 08:03:24 Error: [MethodNotAllowedException] Method Not Allowed
Request URL: /SalvatoresPizza/OrderDetailToppings/delete/2
Stack Trace:
#0 F:\xampp\htdocs\SalvatoresPizza\Controller\OrderDetailToppingsController.php(102): CakeRequest->onlyAllow('post', 'delete')
#1 [internal function]: OrderDetailToppingsController->delete('2')
#2 C:\cake\cakephp-2.4.0\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(OrderDetailToppingsController), Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#4 C:\cake\cakephp-2.4.0\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(OrderDetailToppingsController), Object(CakeRequest), Object(CakeResponse))
#5 F:\xampp\htdocs\SalvatoresPizza\webroot\index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2014-01-15 22:18:34 Error: Fatal Error (1): Maximum execution time of 30 seconds exceeded in [F:\xampp\htdocs\SalvatoresPizza\View\OrderDetails\viewcart.ctp, line 18]
2014-01-15 22:18:34 Error: [FatalErrorException] Maximum execution time of 30 seconds exceeded
Request URL: /SalvatoresPizza/orderdetails/viewcart/1
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Maximum executi...', 'F:\xampp\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(1, 'Maximum executi...', 'F:\xampp\htdocs...', 18, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Maximum executi...', 'F:\xampp\htdocs...', 18, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-15 22:21:34 Error: Fatal Error (4): syntax error, unexpected 'endforeach' (T_ENDFOREACH) in [F:\xampp\htdocs\SalvatoresPizza\View\OrderDetails\viewcart.ctp, line 37]
2014-01-15 22:21:34 Error: [FatalErrorException] syntax error, unexpected 'endforeach' (T_ENDFOREACH)
Request URL: /SalvatoresPizza/orderdetails/viewcart/1
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'F:\xampp\htdocs...', 37)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'F:\xampp\htdocs...', 37, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'F:\xampp\htdocs...', 37, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-15 22:22:33 Error: Fatal Error (4): syntax error, unexpected end of file in [F:\xampp\htdocs\SalvatoresPizza\View\OrderDetails\viewcart.ctp, line 49]
2014-01-15 22:22:33 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /SalvatoresPizza/orderdetails/viewcart/1
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'F:\xampp\htdocs...', 49)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'F:\xampp\htdocs...', 49, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'F:\xampp\htdocs...', 49, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-15 22:24:03 Error: Fatal Error (4): syntax error, unexpected end of file in [F:\xampp\htdocs\SalvatoresPizza\View\OrderDetails\viewcart.ctp, line 49]
2014-01-15 22:24:03 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /SalvatoresPizza/orderdetails/viewcart/1
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'F:\xampp\htdocs...', 49)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'F:\xampp\htdocs...', 49, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'F:\xampp\htdocs...', 49, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-16 22:11:41 Error: Fatal Error (1): Call to a member function find() on a non-object in [F:\xampp\htdocs\SalvatoresPizza\Controller\OrderDetailsController.php, line 260]
2014-01-16 22:11:41 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /SalvatoresPizza/order_details/delete/40
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'F:\xampp\htdocs...', 260)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'F:\xampp\htdocs...', 260, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'F:\xampp\htdocs...', 260, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-16 22:12:12 Error: Fatal Error (1): Call to a member function find() on a non-object in [F:\xampp\htdocs\SalvatoresPizza\Controller\OrderDetailsController.php, line 260]
2014-01-16 22:12:12 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /SalvatoresPizza/order_details/delete/32
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'F:\xampp\htdocs...', 260)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'F:\xampp\htdocs...', 260, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'F:\xampp\htdocs...', 260, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-16 22:13:05 Error: Fatal Error (1): Call to a member function find() on a non-object in [F:\xampp\htdocs\SalvatoresPizza\Controller\OrderDetailsController.php, line 260]
2014-01-16 22:13:05 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /SalvatoresPizza/order_details/delete/32
Stack Trace:
#0 C:\cake\cakephp-2.4.0\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'F:\xampp\htdocs...', 260)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'F:\xampp\htdocs...', 260, Array)
#2 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'F:\xampp\htdocs...', 260, Array)
#3 C:\cake\cakephp-2.4.0\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
